"""Render a completed session as a PDF using ReportLab."""

from __future__ import annotations

import io
from datetime import UTC, datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models import ConsultSession


def render_session_pdf(session: ConsultSession) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    base = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=base["Heading1"], fontSize=18, spaceAfter=4)
    h2 = ParagraphStyle("h2", parent=base["Heading2"], fontSize=12, spaceBefore=12, spaceAfter=4)
    body = ParagraphStyle("body", parent=base["BodyText"], fontSize=10, leading=14)
    meta = ParagraphStyle("meta", parent=base["BodyText"], fontSize=9, textColor=colors.grey)

    flow: list = []
    flow.append(Paragraph("MedScribe AI — Visit Note", h1))
    flow.append(
        Paragraph(
            f"Patient: {_esc(session.patient_label)} &nbsp;&nbsp;|&nbsp;&nbsp; "
            f"Date: {(session.completed_at or session.started_at).strftime('%Y-%m-%d %H:%M')}",
            meta,
        )
    )
    if session.chief_complaint:
        flow.append(Paragraph(f"Chief complaint: {_esc(session.chief_complaint)}", meta))

    flow.append(Spacer(1, 0.15 * inch))

    soap = session.soap_note
    if soap is not None:
        for label, value in (
            ("Subjective", soap.subjective),
            ("Objective", soap.objective),
            ("Assessment", soap.assessment),
            ("Plan", soap.plan),
        ):
            flow.append(Paragraph(label, h2))
            flow.append(Paragraph(_esc(value) or "Not documented", body))

    if session.icd_suggestions:
        flow.append(Paragraph("ICD-10 Suggestions", h2))
        data = [["Code", "Description", "Verified", "Accepted"]]
        for icd in session.icd_suggestions:
            accepted = "—" if icd.accepted_by_user is None else ("Yes" if icd.accepted_by_user else "No")
            data.append(
                [
                    icd.code,
                    _esc(icd.description),
                    "✓" if icd.is_validated else "✗",
                    accepted,
                ]
            )
        table = Table(data, colWidths=[0.9 * inch, 4.0 * inch, 0.8 * inch, 0.8 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f2937")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTSIZE", (0, 0), (-1, -1), 9),
                    ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        flow.append(table)

    if session.visit_summary:
        flow.append(Paragraph("Visit Summary", h2))
        flow.append(Paragraph(_esc(session.visit_summary), body))

    flow.append(Spacer(1, 0.3 * inch))
    flow.append(
        Paragraph(
            f"Generated by MedScribe AI on {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}. "
            "Demo content — not a substitute for clinical judgment.",
            meta,
        )
    )

    doc.build(flow)
    return buffer.getvalue()


def _esc(text: str | None) -> str:
    if text is None:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\n", "<br/>")
    )
